43-6-Apna_Time_Ayega
acmbitmesra/DevHack-0.2 pull request #57
Opened 2019-02-20 19:57 UTC by mynk322

2019-02-21 10:48 UTC, sarthakgupta072 requested changes

2019-02-21 10:48 UTC, sarthak-sopho commented on Leaderboard/After Task-1.md
>    </tr>
Insert your name in b/w the "td" tag.  :P

2019-02-21 10:50 UTC, sarthak-sopho commented
Note: You could have done the changes in the earlier PR too. There was no need to open a separate PR for every change you make.

Close either one of the pull requests.

2019-02-21 19:47 UTC, mynk322 commented
hi

2019-02-22 12:06 UTC, sarthak-sopho commented
I am closing the other pull request. Make changes in this PR only.

2019-02-26 06:56 UTC, closed without merging