53-7-dev_noob
acmbitmesra/DevHack-0.2 pull request #71
Opened 2019-03-11 09:41 UTC by goyaldhara

2019-03-11 14:44 UTC, sarthak-sopho commented
Resolve merge conflict. :)

2019-03-11 17:57 UTC, goyaldhara commented
Resolved the merge conflicts,now please merge my commit

2019-03-11 18:14 UTC, sarthakgupta072 requested changes
Please arrange your team according to the serial number. Here 53 is coming below 55, which should not happen.

2019-03-14 02:15 UTC, sarthakgupta072 approved these changes

2019-03-14 02:16 UTC, merged